apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-distancia
spec:
  spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversao-distancia
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: conversao-distancia
    spec:
      containers:
      - name: conversao-distancia
        image: mathsa/desafio-devops-2025-conversao-distancia:v1
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "50Mi"
            cpu: "20m"
        ports:
          - containerPort: 5000
            name: http-conversao
---
apiVersion: v1
kind: Service
metadata:
  name: conversao-distancia
spec:
  selector:
    app: conversao-distancia
  ports:
  - port: 80
    targetPort: http-conversao
    nodePort: 30000
  type: NodePort

