apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-conversao
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: conversao-distancia
  minReplicas: 1         
  maxReplicas: 10        
  targetCPUUtilizationPercentage: 50  